---
- name: to store in git
  hosts: all
  tasks:
    - name: update system
      apt:
        upgrade: yes
        update_cache: yes
      become: yes
    - name: install git
      apt:
        name: git
        state: latest
    - name: create file
      file:
        path: /root/ansiblefile1
        state: dirctory
      become: yes
